resources:
  containers:
  - container: mssql
    image: microsoft/mssql-server-windows-express
    env: {ACCEPT_EULA: Y, SA_PASSWORD: GLOBAL_PASSWORD}
 
trigger:
- master

pool:
  vmImage: 'windows-latest'
  
services:
  mssql: mssql
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    feedsToUse: 'select'
    versioningScheme: 'off'