resources:
  containers:
  - container: my_container
    image: lukaslansky/visualstudio-netwebworkload
  - container: mssql
    image: microsoft/mssql-server-linux
    env: {ACCEPT_EULA: Y, SA_PASSWORD: GLOBAL_PASSWORD}
 
pool:
  vmImage: 'ubuntu-16.04'
 
container: my_container
 
services:
  mssql: mssql

steps:
- bash: echo ok